### ISSUE TITLE
Add Nav bar

### ISSUE THREAD

**Issue by davinharding** [davinharding/synergy#22]
As a user 
When I am using the app
I would like to see a navbar
so that I am able to navigate from any page to where I would like to go

**Comment by taylorkrause95** [comment]
What will the pages be on the nav bar? Home, Profile, Feed?

**Comment by davinharding** [comment]
Well right now we have SIgn out, and a link to the persons email that sends them to the edit profile page.  I also want to add a link to the feed page which I'm doing now.  So I will head this one up.
